version: 2
updates:
  - package-ecosystem: npm
    directory: "/engine"
    schedule:
      interval: weekly
      day: thursday
      time: "10:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[Chore] "
    cooldown:
      default-days: 3
    groups:
      npm-minor-patch:
        update-types: ["minor", "patch"]
  - package-ecosystem: nuget
    directory: "/exporter"
    schedule:
      interval: weekly
      day: thursday
      time: "10:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[Chore] "
    cooldown:
      default-days: 3
    groups:
      nuget:
        patterns: ["*"]
  - package-ecosystem: docker
    directories: ["/engine", "/exporter"]
    schedule:
      interval: weekly
      day: thursday
      time: "10:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[Chore] "
    cooldown:
      default-days: 3
    groups:
      docker:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "10:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[Chore] "
    cooldown:
      default-days: 3
    groups:
      github-actions:
        patterns: ["*"]
